### ISSUE TITLE
SSL Verify Issue / Internal SMTP Server Crash

### ISSUE THREAD

**Issue by craftyshaun** [beyondcode/helo-community#32]
When trying to use HELO out of the box with a Laravel 5.8 setup and homestead I get an exception. 
![image](https://user-images.githubusercontent.com/774763/82527538-10e54e00-9b7a-11ea-9876-5c719513a3a3.png)

I believe this is due to the internal SMTP server crashing as there is output in the HELO GUI.
![image](https://user-images.githubusercontent.com/774763/82527509-fd39e780-9b79-11ea-94d0-3b6834035084.png)

I think I'm using the latest version as HELO asked me to restart to install an update. 
I tried to click HELO -> About from the menu however nothing happened. Nothing also happened when I clicked the HELP -> Services menu option.

It would be appreciated if anyone could provide any hints

**Comment by craftyshaun** [comment]
@mpociot have you seen this bug before?

**Comment by sschlein** [comment]
Hey @craftyshaun I haven't. There is an issue that HELO sometimes tells you that the server is already running on the 2525 port but we haven't been able to track this down yet.

**Comment by craftyshaun** [comment]
No this one was a TLS issue about the MAC Decode. I'm yet to try running HELO on another machine with the same version of homestead.

**Comment by sschlein** [comment]
I can see that from your screenshot but have no idea where this could come from. There haven't been reports of this before.

**Comment by gchtr** [comment]
I don’t know whether this is connected, but I’m getting a similar error in a WordPress environment in combination with a plugin that updates `PhpMailer` with its own SMTP settings.

<img width="1225" alt="Bildschirmfoto 2020-05-27 um 10 56 46" src="https://user-images.githubusercontent.com/2084481/82999085-ceec5a00-a008-11ea-9df1-55a2c7a523a3.png">

The `phpmailerException` message that I get is the following:

```
SMTP Error: Could not connect to SMTP host.
```

Among the settings of the plugin, there’s the `SMTPSecure` setting, which is set to `tls`, because the SMTP server we normally send mails through requires that.

The default HELO configuration for **WordPress** doesn’t explicitly set that. So when I add `$phpmailer->SMTPSecure = '';` to the default configuration, it works, because I then overwrite the plugin settings:

**Old**

```php
function helo( \PHPMailer $phpmailer) {
    $phpmailer->isSMTP();
    $phpmailer->Host     = '127.0.0.1';
    $phpmailer->SMTPAuth = true;
    $phpmailer->Port     = 2525;
    $phpmailer->Username = 'Mailbox-Name';
    $phpmailer->Password = '';
}
```

**New**

```php
function helo( \PHPMailer $phpmailer) {
    $phpmailer->isSMTP();
    $phpmailer->Host     = '127.0.0.1';
    $phpmailer->SMTPAuth = true;
    $phpmailer->Port     = 2525;
    $phpmailer->Username = 'Mailbox-Name';
    $phpmailer->Password = '';

    // This line helps.
    $phpmailer->SMTPSecure = '';
}
```

**Comment by craftyshaun** [comment]
I think I worked this out.

My `config/mail.php`  had `encryption => 'tls'` and not `encryption => env('MAIL_ENCRYPTION','tls'), ` which meant that TLS was being used when HELO does not support TLS.

@sschlein I'm happy if you close this as user error 😄
