### ISSUE TITLE
Working together to add AdonisJS support to Helo

### ISSUE THREAD

**Issue by thetutlage** [beyondcode/helo-community#40]
Hey guys! 

Helo looks awesome! I see that Helo can work with any library or framework that uses SMTP for sending emails. However, I believe, some extra work is needed for the `Debug` tab.

![](https://usehelo.com/screenshots/debug.png)

I tried reading the docs, didn't found anything there. Do you think, you can point me to the correct resource in order to provide the similar debug information for AdonisJS as well?

**Comment by sschlein** [comment]
Hey @thetutlage !

We just realized that this piece is not documented yet. We'll add this asap.

In the meantime, you can have a look at the Laravel example here: 
https://github.com/beyondcode/helo-laravel/blob/master/src/Mailer.php#L27-L50

Please let us know if you have something generic for AdonisJS so that we can include it in the docs.

**Comment by thetutlage** [comment]
Hey @sschlein 

That looks very simple. Will get it rolling in AdonisJS too.

Regarding the generic settings. Yes, has to be defined inside the `.env` file.

```
SMTP_HOST=127.0.0.1
SMTP_PORT=2525
SMTP_USERNAME=Inbox-Name
SMTP_PASSWORD=
```
